title:              Corona
email:              
description:        A Virtual Mass Spectrometer
author:             Michael Hoopmann and Devin Schweppe
baseurl:            "/Corona"
url:                "https://schweppelab.github.io"
repourl:            "https://github.com/SchweppeLab/Corona"

# Social Profiles
twitter_username:   
github_username:    SchweppeLab
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
